# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-01 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0105_auto_20180101_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHEMBLTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chembl_id', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
