# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-01 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0106_chembltarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='related_ChEMBL_targets',
            field=models.ManyToManyField(blank=True, null=True, to='compounds.CHEMBLTarget'),
        ),
    ]
