# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0107_compound_related_chembl_targets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='related_ChEMBL_targets',
            field=models.ManyToManyField(blank=True, to='compounds.CHEMBLTarget'),
        ),
    ]
