# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0109_herb_chinese_synonyms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herb',
            name='source_id',
        ),
        migrations.AddField(
            model_name='herb',
            name='link_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
