# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0110_auto_20180201_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='herb_class_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
