# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0111_herb_herb_class_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herb',
            old_name='herb_class_id',
            new_name='related_id',
        ),
        migrations.RenameField(
            model_name='herb',
            old_name='link_id',
            new_name='sub_herb_link_id',
        ),
    ]
