# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0112_auto_20180201_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='first_catagory_chinese',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='herb',
            name='first_catagory_english',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='herb',
            name='second_catagory_chinese',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='herb',
            name='second_catagory_english',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
