# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0113_auto_20180201_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='wiki_chinese',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herb',
            name='wiki_english',
            field=models.URLField(blank=True, null=True),
        ),
    ]
