# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0116_auto_20180201_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='related_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herb',
            name='sub_herb_link_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
