# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0117_auto_20180201_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herb',
            name='related_herbs',
        ),
    ]
