# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0119_herb_related_herbs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubHerb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chinese_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('Chinese_synonyms', models.CharField(blank=True, max_length=1024, null=True)),
                ('pinyin_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('English_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('latin_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('first_catagory_chinese', models.CharField(blank=True, max_length=1024, null=True)),
                ('first_catagory_english', models.CharField(blank=True, max_length=1024, null=True)),
                ('second_catagory_chinese', models.CharField(blank=True, max_length=1024, null=True)),
                ('second_catagory_english', models.CharField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='herb_images')),
                ('wiki_english', models.URLField(blank=True, null=True)),
                ('wiki_chinese', models.URLField(blank=True, null=True)),
                ('drug_property', models.CharField(blank=True, max_length=1024, null=True)),
                ('meridians', models.CharField(blank=True, max_length=1024, null=True)),
                ('use_part', models.CharField(blank=True, max_length=1024, null=True)),
                ('effect', models.CharField(blank=True, max_length=1024, null=True)),
                ('indication', models.CharField(blank=True, max_length=1024, null=True)),
                ('related_id', models.IntegerField(blank=True, null=True)),
                ('sub_herb_link_id', models.IntegerField(blank=True, null=True)),
                ('taxonomy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.TCMTaxonomy')),
            ],
        ),
    ]
