# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0121_subherb_herb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subherb',
            name='Chinese_synonyms',
        ),
    ]
