# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-03 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0122_remove_subherb_chinese_synonyms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='english_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
